on:
  push:
    branches:
      - master

    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - name: Docker build api admin
        if: github.ref == 'refs/heads/master' || contains(github.ref, 'tags')
        run: docker build -f docker/api-admin/Dockerfile -t registry.gitlab.com/upview/core-api-images/api-admin:latest .

      - name: Gitlab registry login
        if: github.ref == 'refs/heads/master' || contains(github.ref, 'tags')
        run: docker login -u gitlab-ci-token -p ${{ secrets.GITLAB_ACCESS_TOKEN }} registry.gitlab.com

      - name: Push docker api admin image
        if: github.ref == 'refs/heads/master'
        run: docker push registry.gitlab.com/upview/core-api-images/api-admin

      - name: Get tag name
        id: get_tag_name
        if: contains(github.ref, 'tags')
        run: echo ::set-output name=TAG_NAME::${GITHUB_REF#refs/tags/}

      - name: Tag docker api admin image
        if: contains(github.ref, 'tags')
        run: docker tag registry.gitlab.com/upview/core-api-images/api-admin:latest registry.gitlab.com/upview/core-api-images/api-admin:${{ steps.get_tag_name.outputs.TAG_NAME }}

      - name: Push tagged docker api admin image
        if: contains(github.ref, 'tags')
        run: docker push registry.gitlab.com/upview/core-api-images/api-admin:${{ steps.get_tag_name.outputs.TAG_NAME }}
