on:
  push:
    branches:
      - master

    tags:
      - '*'

  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [12.x]

    services:
      postgres:
        image: postgres:10.6-alpine
        env:
          POSTGRES_DB: test
        ports:
        - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      redis:
        image: redis:3.2.6-alpine
        ports:
        - 6379/tcp
        options: --entrypoint redis-server

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run:  yarn install --frozen-lockfile

    - name: Lint
      run: yarn lint

    - name: Test
      run: yarn test
      env:
        DATABASE_HOST: localhost
        DATABASE_PORT: ${{ job.services.postgres.ports[5432] }}
        REDIS_HOST: localhost
        REDIS_PORT: ${{ job.services.redis.ports[6379] }}

    - name: Docker build
      if: github.ref == 'refs/heads/master'
      run: docker build -f docker/api-admin/Dockerfile -t registry.gitlab.com/upview/core-api-images/api-admin:latest .

    - name: Gitlab registry login
      if: github.ref == 'refs/heads/master' || contains(github.ref, 'tags')
      run: docker login -u gitlab-ci-token -p ${{ secrets.GITLAB_ACCESS_TOKEN }} registry.gitlab.com

    - name: Push docker master image
      if: github.ref == 'refs/heads/master'
      run: docker push registry.gitlab.com/upview/core-api-images/api-admin

    - name: Get tag name
      id: get_tag_name
      if: contains(github.ref, 'tags')
      run: echo ::set-output name=TAG_NAME::${GITHUB_REF#refs/tags/}

    - name: Tag docker image
      if: contains(github.ref, 'tags')
      run: docker tag registry.gitlab.com/upview/core-api-images/api-admin:latest registry.gitlab.com/upview/core-api-images/api-admin:${{ steps.get_tag_name.outputs.TAG_NAME }}

    - name: Push tagged docker image
      if: contains(github.ref, 'tags')
      run: docker push registry.gitlab.com/upview/core-api-images/api-admin:${{ steps.get_tag_name.outputs.TAG_NAME }}
