on:
  push:
    tags:
      - '*'
jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - name: Deploy to Heroku
        run: git push https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_API_ADMIN_APP }}.git HEAD:master
